version: "3.9"
services:
  sentinel-compliance:
    build: .
    container_name: sentinel-compliance
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: "8364788981:AAGxzOf8m65Rd9PVJrASoaZw-0STOBwgcwY"
      TELEGRAM_CHAT_ID: "5784319128"
    ports:
      - "3000:3000"

  sentinel-dashboard:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "https://api.sentinelsol.live"
    container_name: sentinel-dashboard
    restart: always
    depends_on:
      - sentinel-compliance
    ports:
      - "4173:4173"
